name: make-test

on:
  push:
    branches: [main] 

jobs:
  build-worksheet7:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Configure CMake 
      run: cd Worksheet7
      run: cmake -B ${{github.workspace}}/build Exercise2

    - name: Build
      working-directory: ${{github.workspace}}/build 
      run: make


    - name: Test
      working-directory: ${{github.workspace}}/build
      run: make test